name: flutter_round_slider
description: A Flutter package to create a Round Slider. It will be useful for your awesome app.
version: 1.0.0
homepage: https://romanticdeveloper.com
repository: https://github.com/minhhung2556/romantic_project_flutter_round_slider

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true